### PR TITLE
add tests for object properties after array path

### PR DESCRIPTION
**Pull request by narcoticfresh**
so this should fail now, but be green after raphaelstolt/php-jsonpointer#11 has been merged and a new tag exists..

@raphaelstolt please re-run travis after the tag in `raphaelstolt/php-jsonpointer`..

thanks!

### CODE REVIEW

**Comment by raphaelstolt** [comment]
Closed with edc2aa52655a1c0a6f5a29e36efa98e19774c5f7.

**Comment by narcoticfresh** [comment]
@raphaelstolt could you please tag `3.0.2`?

**Comment by raphaelstolt** [comment]
Hm there were only tests added which doesn't  justify a version raise.

**Comment by narcoticfresh** [comment]
@raphaelstolt ah yes, you're right ;-) ok..

**Pull request closed without merging**
