### PR TITLE
Extract base exception class

### PR DESCRIPTION
**Pull request by megazoll**
For simpler catching library exceptions from own stuff.

### CODE REVIEW

**Comment by raphaelstolt** [comment]
Not quite sure about this one, as it might introduce a breaking change and library specific exceptions (e.g. `InvalidTargetDocumentJsonException`, `InvalidPatchDocumentJsonException`, and `InvalidOperationException`) are already thrown and therefor _simply_ catchable. 

Also there's no point in the current codebase where a _core_ `Exception` (i.e. `BaseException`) is thrown.

**Comment by megazoll** [comment]
This change should not introduce any breaking change, because current exceptions stay the same and will catch with same signatures.
With this change we can catch in own code base exception to catch _all_ library exceptions, i.e.:
```php
try {
    $patch = new Patch($document, $patchOperations);
} catch (\Rs\Json\Patch\Exception) {
    // do anything
}
```
but now we should have 4 ``catch`` blocks for each exception class and all introduced in future exceptions will not be catched.

**Comment by raphaelstolt** [comment]
Closed with [#8f948f3](https://github.com/raphaelstolt/php-jsonpatch/commit/8f948f3437f2490c7f82bca1bb70e34ad95eda86).

**Comment by raphaelstolt** [comment]
Closed with [#8f948f3](https://github.com/raphaelstolt/php-jsonpatch/commit/8f948f3437f2490c7f82bca1bb70e34ad95eda86).

**Comment by megazoll** [comment]
Thank you!

**Pull request closed without merging**
