### PR TITLE
Add ability to disable patch operations by bitmask

### PR DESCRIPTION
**Pull request by mikelohmann**
I could be useful to disallow some operations on a document (like remove). Therefore it is possible to set a value for each patch operation which should be allowed to use. Per default all are allowed.

### CODE REVIEW

**Comment by mikelohmann** [comment]
Thanks for your comments. I think I met the expectations.

**Comment by raphaelstolt** [comment]
Could you rebase your branch and squash your commits into a single one (feel free to do a forced push against your PR branch)?

**Comment by mikelohmann** [comment]
Sure.

**Comment by mikelohmann** [comment]
Ideas regarding 5.4 and 5.5?

**Comment by raphaelstolt** [comment]
To fix the PHP 5.4 and 5.5 failing tests just initalize `allowedPatchOperations` inside the constructor.

**Comment by mikelohmann** [comment]
Ok. Did that. Seems to work.

**Comment by raphaelstolt** [comment]
👍 Will merge and roll out a new release. Thanks for the contribution.

**Comment by mikelohmann** [comment]
Great. Thanks for the fast responses.

**Comment by raphaelstolt** [comment]
Merged with 69561f64240d16a591dedc0538f95a2509723f60.

**Pull request closed without merging**
